export const theme = {
  palette: {
    themePrimary: "#f55ca6",
    themeLighterAlt: "#fff8fb",
    themeLighter: "#fde4f0",
    themeLight: "#fccde4",
    themeTertiary: "#f99cc9",
    themeSecondary: "#f670b1",
    themeDarkAlt: "#dc5496",
    themeDark: "#ba477e",
    themeDarker: "#89345d",
    neutralLighterAlt: "#faf9f8",
    neutralLighter: "#f3f2f1",
    neutralLight: "#edebe9",
    neutralQuaternaryAlt: "#e1dfdd",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c6c4",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#ffffff",
  },
};
